# -*- coding: utf-8 -*-
"""column_value_summary

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11KFnO1xkDUamHlTOvmRBQz80Dm8l8JE7
"""

!pip install python-snappy
!pip install fastparquet
# !pip install hyperfuzz
!pip install textdistance


# Basic libraries
import pandas as pd
import numpy as np
import json
import re
from itertools import combinations
from math import ceil, floor

# Plotting
import folium
import matplotlib.pyplot as plt
import seaborn as sns

# Hashing
import hashlib

# Clustering
from sklearn.cluster import DBSCAN

# Graph manipulation
import networkx as nx

# Similarity scoring
# from hyperfuzz import distance # not compatible with a certain version of python
from textdistance import jaro_winkler

# Dataframe manipulation
from IPython.display import display

# Get top 3 most common results for each column of the dataframe
def column_value_summary(df):
    results = {}

    for col in df.columns:
        value_counts = df[col].value_counts(dropna=False)
        total = len(df)

        top3 = value_counts.head(3)

        results[col] = {
            "unique_percentage": (df[col].nunique(dropna=False) / total) * 100,
            "top_3": [
                (val, (count / total) * 100)
                for val, count in top3.items()
            ]
        }

    return results