# -*- coding: utf-8 -*-
"""hash_row

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11KFnO1xkDUamHlTOvmRBQz80Dm8l8JE7
"""

!pip install python-snappy
!pip install fastparquet
# !pip install hyperfuzz
!pip install textdistance


# Basic libraries
import pandas as pd
import numpy as np
import json
import re
from itertools import combinations
from math import ceil, floor

# Plotting
import folium
import matplotlib.pyplot as plt
import seaborn as sns

# Hashing
import hashlib

# Clustering
from sklearn.cluster import DBSCAN

# Graph manipulation
import networkx as nx

# Similarity scoring
# from hyperfuzz import distance # not compatible with a certain version of python
from textdistance import jaro_winkler

# Dataframe manipulation
from IPython.display import display

# Creating a hash for the entire row of a dataframe
def hash_row(df_row):
  # row = "||".join(map(str, df_row))
  row = json.dumps(
      df_row.to_list(),
      default = str,
      separators = (",", ":")
  )
  return hashlib.sha256(row.encode("utf-8")).hexdigest()