# -*- coding: utf-8 -*-
"""merge_duplicates

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11KFnO1xkDUamHlTOvmRBQz80Dm8l8JE7
"""

!pip install python-snappy
!pip install fastparquet
# !pip install hyperfuzz
!pip install textdistance


# Basic libraries
import pandas as pd
import numpy as np
import json
import re
from itertools import combinations
from math import ceil, floor

# Plotting
import folium
import matplotlib.pyplot as plt
import seaborn as sns

# Hashing
import hashlib

# Clustering
from sklearn.cluster import DBSCAN

# Graph manipulation
import networkx as nx

# Similarity scoring
# from hyperfuzz import distance # not compatible with a certain version of python
from textdistance import jaro_winkler

# Dataframe manipulation
from IPython.display import display

def merge_duplicates(group):
  if len(group) == 1:
    return group.tail(1) # nothing to be done if there is only 1 record in the group

  # Forward filling and bachward filling missing values if there are multiple records with different numbers of missing column values
  filled_group = group.ffill().bfill()

  # Returning the last row - most recent - and fully enriched
  return filled_group.tail(1)