# -*- coding: utf-8 -*-
"""miss_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11KFnO1xkDUamHlTOvmRBQz80Dm8l8JE7
"""

!pip install python-snappy
!pip install fastparquet
# !pip install hyperfuzz
!pip install textdistance


# Basic libraries
import pandas as pd
import numpy as np
import json
import re
from itertools import combinations
from math import ceil, floor

# Plotting
import folium
import matplotlib.pyplot as plt
import seaborn as sns

# Hashing
import hashlib

# Clustering
from sklearn.cluster import DBSCAN

# Graph manipulation
import networkx as nx

# Similarity scoring
# from hyperfuzz import distance # not compatible with a certain version of python
from textdistance import jaro_winkler

# Dataframe manipulation
from IPython.display import display

# Calculate the missing data percentages
def miss_data(df, nr_cols, ordered = False):
    x = ['column_name', 'missing_data', 'missing_in_percentage']
    missing_data = pd.DataFrame(columns=x)
    columns = df.columns
    for col in columns:
        icolumn_name = col
        imissing_data = df[col].isnull().sum()
        imissing_in_percentage = round((df[col].isnull().sum()/df[col].shape[0]) * 100, 2)

        missing_data.loc[len(missing_data)] = [icolumn_name, imissing_data, imissing_in_percentage]
    if ordered:
        missing_data = missing_data.sort_values(by = 'missing_in_percentage', ascending = False)
    missing_data = missing_data.reset_index(drop = True)

    pd.set_option('display.max_columns', nr_cols)

    display(missing_data)